const ErrorCodes = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_TOKEN: "INVALID_TOKEN",
  DATA_INVALID: "DATA_INVALID",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
};

export default ErrorCodes;
